name: social_app
description: Social App with Firebase.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Functional programming in Dart.
  dartz: ^0.9.1

  # Firebase Service.
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  google_sign_in: ^4.5.3

  # Flutter package that helps implement the BLoC pattern.
  flutter_bloc: ^6.0.5

  # Annotation for package freezed.
  freezed_annotation: ^0.11.0+1

  # This is a simple Service Locator for Dart and Flutter projects.
  get_it: ^4.0.4

  # Injectable is a convenient code generator for get_it.
  injectable: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Auto route generator.
  auto_route_generator: ^0.6.8

  # A build system for Dart code generation and modular compilation.
  build_runner: ^1.10.1

  # Another code generator for unions/pattern-matching/copy.
  # Also has sealed class generator.
  freezed: ^0.11.6

  # Generator of injectable.
  injectable_generator: ^1.0.4

  # Is a hand-picked, open-source, community-driven collection of lint rules for Dart and Flutter projects.
  # This package can be used as a replacement for pedantic for those who prefer stricter rules.
  lint: ^1.2.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
